# Generated by Syncropel
from __future__ import annotations
from pydantic import BaseModel


class UsersGetByUsernameParameters(BaseModel):
    """Parameters for the `getUser` action."""

    username: str
