# /.github/workflows/release.yml

name: Test and Release CX Shell

on:
  push:
    tags:
      - "v*" # Trigger on any tag like v0.1.0

jobs:
  test:
    name: Run Unit & Integration Tests (via Nix)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # --- START OF DEFINITIVE FIX ---
      - name: Install Nix (Modern Version)
        # Use a newer version of the action to get a modern Nix.
        uses: cachix/install-nix-action@v27
        with:
          # Pin to a stable channel for CI to prevent breakages from `nixos-unstable`.
          # This is a best practice for CI stability.
          nix_path: nixpkgs=channel:nixos-23.11
      # --- END OF DEFINITIVE FIX ---

      - name: Run Pytest inside the hermetic devShell
        run: |
          # The devShell defined in flake.nix installs all dependencies.
          # We can run our tests directly within it.
          nix develop --command python -m pytest

  create-release:
    name: Create GitHub Release
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release from Git Tag
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
