# /.github/workflows/release.yml

name: Test and Release CX Shell

on:
  push:
    tags:
      - "v*" # Trigger on any tag like v0.1.0

jobs:
  test:
    name: Run Unit & Integration Tests (via Nix)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-23.11

      - name: Run Pytest inside the hermetic devShell
        run: |
          # This command enters the Nix development environment defined in flake.nix,
          # which has all dependencies (Python, uv, pytest) pre-installed.
          # It then executes our test suite. This ensures our CI tests run in an
          # environment identical to our local development setup.
          nix develop --command python -m pytest

  create-release:
    name: Create GitHub Release
    # This job only runs if the 'test' job completes successfully.
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets.
    steps:
      - name: Create GitHub Release from Git Tag
        uses: softprops/action-gh-release@v2
        with:
          # This automatically creates a new GitHub Release page based on the
          # Git tag that triggered this workflow.
          generate_release_notes: true
          # NOTE: There is no 'files' key. We are intentionally not uploading any
          # binary artifacts. The source code at this tag is the release.
